### ISSUE TITLE
Tensorflow2.0 support?

### ISSUE THREAD

**Issue by oliverdutton** [farizrahman4u/recurrentshop#117]
Is there support for Tensorflow 2.0 because currently 

'import tensorflow as tf
from recurrentshop import *

rnn = RecurrentSequential(unroll=False, return_sequences=False)
rnn.add(SimpleRNNCell(10, input_dim=5))
rnn.add(Dense(5))'

runs perfectly in tf1.14 but not in tf2.0

In tf2.0 you immediately hit an error:
'Using TensorFlow backend.
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    rnn = RecurrentSequential(unroll=False, return_sequences=False)
  File "/Users/sj18703/anaconda3/envs/tf2.0/lib/python3.7/site-packages/recurrentshop-1.0.0-py3.7.egg/recurrentshop/engine.py", line 885, in __init__
  File "/Users/sj18703/anaconda3/envs/tf2.0/lib/python3.7/site-packages/Keras-2.2.4-py3.7.egg/keras/legacy/layers.py", line 440, in __init__
    super(Recurrent, self).__init__(**kwargs)
  File "/Users/sj18703/anaconda3/envs/tf2.0/lib/python3.7/site-packages/Keras-2.2.4-py3.7.egg/keras/engine/base_layer.py", line 132, in __init__
    name = _to_snake_case(prefix) + '_' + str(K.get_uid(prefix))
  File "/Users/sj18703/anaconda3/envs/tf2.0/lib/python3.7/site-packages/Keras-2.2.4-py3.7.egg/keras/backend/tensorflow_backend.py", line 74, in get_uid
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph''

Will tf2.0 be supported and how much work would that take?

**Comment by n1lsh** [comment]
In TF 2.0 you should get rid of keras standalone and simply add the following lines to the top of engine.py

```
import tensorflow.keras as keras
from keras import backend as K
```
