### ISSUE TITLE
ImportError: cannot import name 'tensorflow_backend'

### ISSUE THREAD

**Issue by jlunit** [farizrahman4u/recurrentshop#124]
I keep getting this error below when I try to import the package:

from recurrentshop import *
  File "/usr/local/lib/python3.6/dist-packages/recurrentshop-1.0.0-py3.6.egg/recurrentshop/__init__.py", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/recurrentshop-1.0.0-py3.6.egg/recurrentshop/engine.py", line 4, in <module>
  File "/usr/local/lib/python3.6/dist-packages/recurrentshop-1.0.0-py3.6.egg/recurrentshop/backend/__init__.py", line 5, in <module>
  File "/usr/local/lib/python3.6/dist-packages/recurrentshop-1.0.0-py3.6.egg/recurrentshop/backend/tensorflow_backend.py", line 1, in <module>
ImportError: cannot import name 'tensorflow_backend'

What might be the problem?

**Comment by mikhail0920** [comment]
Same problem!

**Comment by Mubashir4** [comment]
Same problem...


File "/home/s4523139/codes/Seq2Seq/TestCode/test.py", line 8, in <module>
    from seq2seq import SimpleSeq2Seq, Seq2Seq, AttentionSeq2Seq

File "/home/s4523139/anaconda3/lib/python3.8/site-packages/seq2seq/__init__.py", line 1, in <module>
    from .cells import *

File "/home/s4523139/anaconda3/lib/python3.8/site-packages/seq2seq/cells.py", line 1, in <module>
    import recurrentshop

File "<frozen zipimport>", line 259, in load_module

File "/home/s4523139/anaconda3/lib/python3.8/site-packages/recurrentshop-1.0.0-py3.8.egg/recurrentshop/__init__.py", line 1, in <module>
    from .engine import *

File "<frozen zipimport>", line 259, in load_module

File "/home/s4523139/anaconda3/lib/python3.8/site-packages/recurrentshop-1.0.0-py3.8.egg/recurrentshop/engine.py", line 4, in <module>
    from .backend import rnn, learning_phase_scope

File "<frozen zipimport>", line 259, in load_module

File "/home/s4523139/anaconda3/lib/python3.8/site-packages/recurrentshop-1.0.0-py3.8.egg/recurrentshop/backend/__init__.py", line 5, in <module>
    from .tensorflow_backend import *

File "<frozen zipimport>", line 259, in load_module

File "/home/s4523139/anaconda3/lib/python3.8/site-packages/recurrentshop-1.0.0-py3.8.egg/recurrentshop/backend/tensorflow_backend.py", line 1, in <module>
    from keras.backend import tensorflow_backend as K

ImportError: cannot import name 'tensorflow_backend' from 'keras.backend' (/home/s4523139/anaconda3/lib/python3.8/site-packages/keras/backend.py)

**Comment by sablea** [comment]
same problem
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-9cd2096d0776> in <module>()
----> 1 from recurrentshop import RecurrentSequential,LSTMCell
      2 from recurrentshop.cells import LSTMDecoderCell, AttentionDecoderCell

3 frames
/content/recurrentshop/backend/tensorflow_backend.py in <module>()
----> 1 from keras.backend import tensorflow_backend as K
      2 import tensorflow as tf
      3 
      4 
      5 class learning_phase_scope(object):

ImportError: cannot import name 'tensorflow_backend' from 'keras.backend' (/usr/local/lib/python3.7/dist-packages/keras/backend.py)

**Comment by sametapizza** [comment]
Same problem...

**Comment by amaralcs** [comment]
Hey all, not sure this is still relevant to you but I found in another issue that using Keras==2.2.4 solves some issues, and it also solved this particular issue for me.

**Comment by Hiilion** [comment]
same error
Traceback (most recent call last):

  File "D:\SpyderProjects\TensorflowProjects\POL_seq2seq\POLwithseq2seq.py", line 8, in <module>
    import recurrentshop

  File "<frozen zipimport>", line 259, in load_module

  File "D:\Application\Python3.8.10\lib\site-packages\recurrentshop-1.0.0-py3.8.egg\recurrentshop\__init__.py", line 1, in <module>
    from .engine import *

  File "<frozen zipimport>", line 259, in load_module

  File "D:\Application\Python3.8.10\lib\site-packages\recurrentshop-1.0.0-py3.8.egg\recurrentshop\engine.py", line 4, in <module>
    from .backend import rnn, learning_phase_scope

  File "<frozen zipimport>", line 259, in load_module

  File "D:\Application\Python3.8.10\lib\site-packages\recurrentshop-1.0.0-py3.8.egg\recurrentshop\backend\__init__.py", line 5, in <module>
    from .tensorflow_backend import *

  File "<frozen zipimport>", line 259, in load_module

  File "D:\Application\Python3.8.10\lib\site-packages\recurrentshop-1.0.0-py3.8.egg\recurrentshop\backend\tensorflow_backend.py", line 1, in <module>
    from keras.backend import tensorflow_backend as K

ImportError: cannot import name 'tensorflow_backend' from 'keras.backend' (D:\Application\Python3.8.10\lib\site-packages\keras\backend.py)

**Comment by Hiilion** [comment]
recurrent的最近一次更新是2019年。
tensorflow-2.2.0版本为2019年10月。
可以试试更换tensrflow和keras版本为2.2.0
我已经用此方法解决该问题

**Comment by DaniloSerna** [comment]
I have the same issue, but I am working inside the CMSSW environment:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'tensorflow_backend' from 'keras.backend' (/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/py3-Keras/2.4.3-llifpc2/lib/python3.9/site-packages/keras/backend.py)
<FATAL>                         : 
***> abort program execution

Does someone know how can I change the Keras and Tensorflow version inside the cmsenv?
Thanks in advance!

**Comment by Zhangmazi6666** [comment]
> recurrent的最近一次更新是2019年。 tensorflow-2.2.0版本为2019年10月。 可以试试更换tensrflow和keras版本为2.2.0 我已经用此方法解决该问题

I think that U are correct. The project hasn't been updated for a long time, so we should use the old version keras and tensorflow too.

**Comment by Zhangmazi6666** [comment]
> Hey all, not sure this is still relevant to you but I found in another issue that using Keras==2.2.4 solves some issues, and it also solved this particular issue for me.

I think that U are correct. The project hasn't been updated for a long time, so we should use the old version keras and tensorflow too.
